# Use the node 20 alpine image
FROM node:20-alpine

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json files to the working directory
COPY package*.json .

# Install the dependencies
RUN npm install

# Copy the rest of the files to the working directory
COPY . .

EXPOSE 5173

# Start the development server
CMD ["npm", "run", "dev"]
