version: "1"

services:
  client:
    image: mhackmann18/qs-client:dev
    ports:
      - 127.0.0.1:5173:5173
    volumes:
      - ./client/src:/app/src
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    environment:
      - VITE_FIREBASE_API_KEY
      - VITE_FIREBASE_PROJECT_ID
      - VITE_FIREBASE_APP_ID
      - VITE_FIREBASE_PROJECT_NUMBER
    depends_on:
      - api

  api:
    image: mhackmann18/qs-api:dev
    ports:
      - 127.0.0.1:5274:5274
    volumes:
      - ./api:/app
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    environment:
      JWT_SECRET_FILE: /run/secrets/jwt_secret
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_password
      FIREBASE_CREDENTIALS_FILE: /run/secrets/firebase_pk
      DB_HOST: db
    secrets:
      - jwt_secret
      - mysql_password
      - firebase_pk

  db:
    image: mhackmann18/qs-db:dev
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - data:/var/lib/mysql
    build:
      context: ./db
      dockerfile: Dockerfile.dev
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_password
    secrets:
      - mysql_password

secrets:
  mysql_password:
    file: mysql_password.txt
  jwt_secret:
    file: jwt_secret.txt
  firebase_pk:
    file: firebase-pk.json

volumes:
  data:
