# Use the official MySQL image
FROM mysql:8.0

# Set environment variables
ENV MYSQL_DATABASE=queuing_system

# When container starts, this script will be executed
COPY ./sql-scripts/ /docker-entrypoint-initdb.d/
